#!/bin/bash

CUSTOMER=$1 
COMPANY=$2
BITS=2064 # Weird, huh? 2048 is sufficient per man page http://linux.die.net/man/1/ssh-keygen
LOCATION=keys
PUBKEY=$LOCATION/id_rsa_${CUSTOMER}.pub
KEY=$LOCATION/id_rsa_${CUSTOMER}
MAIL="ecalvo_${COMPANY}"

[[ -d $LOCATION ]] || mkdir $LOCATION

ssh-keygen -C ${CUSTOMER}_${MAIL} -f $KEY -t rsa -b $BITS || exit 2

cat $PUBKEY || exit 1

exit 0
