#!/bin/bash

TUNED="/etc/postgresql/10/main/postgresql.conf.tuned"
CONF="/etc/postgresql/10/main/postgresql.conf"
SAMPLE="/etc/postgresql/10/main/postgresql.conf.sample"
PGDB="ongres"
FULLLOG="bench.log"
SECS=${1:-300}

function test(){
  for conns in 100 300 500 700 900
  do
    printf "### ${conns} \n" >> ${FULLLOG}_${TEST}
    pgbench -n -r --time=${SECS} -c ${conns} ${PGDB} >> ${FULLLOG}_${TEST} 
  done

  fuckcache
}

function setdef(){
  cp $SAMPLE $CONF
  TEST="DEFAULT"
  printf "## DEFAULT \n" >> ${FULLLOG}_${TEST}
}

function settuned(){
  cp $TUNED $CONF
  TEST="TUNED"
  printf "## TUNED \n" >> ${FULLLOG}_${TEST}
}

function fuckcache(){
  sudo bash -c "sync && echo 3 > /proc/sys/vm/drop_caches"
}

function vacan(){
  vacuumdb $PGDB
}

vacan
setdef
test
vacan
settuned
test

exit 0
